server:
   port: 3000
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: authentiction-server
  
logging:
   level:
     ROOT: DEBUG

jwt:
  expiration: 108000