server:
   port: 3000
  
spring:
  application:
    name: nlpcloud-authz-service
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  security:
      oauth2:
        jwt:
          signingKey: qw$c%AeJr(Lew$%$^&&DNcdtyop/.,%&.rxv5.com
          #过期时间，单位(分)
          expiration: 30
      client:
        client-id: nalipei-client
        client-secret: nalipei-secret
        user-authorization-uri: http://localhost:3000/oauth/authorize
        grant-type: password
        client.scope: all
        access-token-uri: http://localhost:3000/oauth/token
      authorization:
        check-token-access: http://localhost:3000/oauth/check_token
      resource:
        token-info-uri: http://localhost:3000/oauth/check_token

logging:
   level:
     ROOT: DEBUG
